# Generated by Django 6.0.2 on 2026-04-07 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('crop_type', models.CharField(choices=[('CACAO', 'Cacao'), ('RICE', 'Rice'), ('BANANA', 'Banana'), ('VEGETABLES', 'Vegetables'), ('CORN', 'Corn')], max_length=20)),
                ('area_hectares', models.FloatField(default=1.0)),
                ('installed_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('disease_type', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('probability', models.FloatField()),
                ('recommendation', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_risks', to='farm.farm')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('needed', models.BooleanField()),
                ('water_amount_liters', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('days_until_next', models.IntegerField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_recs', to='farm.farm')),
            ],
        ),
        migrations.CreateModel(
            name='SensorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_date', models.DateField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='farm.farm')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('soil_moisture', models.FloatField(help_text='Percentage')),
                ('soil_temperature', models.FloatField(help_text='Celsius')),
                ('soil_pH', models.FloatField()),
                ('air_temperature', models.FloatField(help_text='Celsius')),
                ('humidity', models.FloatField(help_text='Percentage')),
                ('leaf_wetness', models.FloatField(help_text='Percentage')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='farm.sensornode')),
            ],
        ),
        migrations.CreateModel(
            name='YieldForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('predicted_yield_kg', models.FloatField()),
                ('harvest_date', models.DateField()),
                ('confidence', models.FloatField(help_text='Percentage')),
                ('crop_condition', models.CharField(max_length=50)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_forecasts', to='farm.farm')),
            ],
        ),
    ]
